### ISSUE TITLE
RoomAI can't supported python3

### ISSUE THREAD

**Issue by arixlin** [roomai/RoomAI#16]
Traceback (most recent call last):
  File "roomaitest.py", line 2, in <module>
    from roomai.kuhn import *;
  File "D:\ProgramData\Anaconda3\envs\python36\lib\site-packages\roomai\__init__.py", line 2, in <module>
    from RoomAILogger import *
ModuleNotFoundError: No module named 'RoomAILogger'

**Comment by algorithmdog** [comment]
Thank you for your attention.
You can upgrade RoomAI to the newest version by "pip install roomai==0.1.3"
We have fixed this bug in the newest version.

**Comment by arixlin** [comment]
@algorithmdog 赞！

**Comment by algorithmdog** [comment]
In Python3, dict.values() returns the dict_values, rather than list.
You can change this line to "return list(self.available_actions.values())[int(random.random() * len(self.available_actions))]"

May I have your WeChat. Mine is liletal. We are looking forward for users' suggestions

**Comment by algorithmdog** [comment]
In Python3, dict.values() returns the dict_values, rather than list.
You can change this line to "return list(self.available_actions.values())[int(random.random() * len(self.available_actions))]"
