### ISSUE TITLE
testDouDiZhuPokerEnv.py error

### ISSUE THREAD

**Issue by arixlin** [roomai/RoomAI#17]
Traceback (most recent call last):
  File "D:/github/RoomAI/testDouDiZhuPokerEnv.py", line 31, in <module>
    env.compete(env, players)
  File "D:\github\RoomAI\roomai\doudizhupoker\DouDiZhuPokerEnv.py", line 226, in compete
    players[i].receive_info(infos[i])
  File "D:/github/RoomAI/testDouDiZhuPokerEnv.py", line 15, in receive_info
    self.actions = info.person_state.available_actions
  File "D:\github\RoomAI\roomai\common\common.py", line 88, in __get_available_actions__
    def __get_available_actions__(self):  return FrozenDict(self.__available_actions__)
AttributeError: 'DouDiZhuPersonState' object has no attribute '__available_actions__'

**Comment by algorithmdog** [comment]
I will solve this problem as soon as possible

**Comment by algorithmdog** [comment]
Are you Chinese ？

**Comment by algorithmdog** [comment]
we are extremely sorry for that we have removed the DouDiZhu game from RoomAI. The reason is complex, and we are willing to bring it back to RoomAI.
Very sorry.

**Comment by arixlin** [comment]
@algorithmdog  嗯， 谢谢  你们的项目很赞！正在学习
