### ISSUE TITLE
Bridge deepcopy error

### ISSUE THREAD

**Issue by abcp4** [roomai/RoomAI#25]
There seems to be error on the deepcopy method for the bridge game. 

`
Traceback (most recent call last):
  File "testBridge.py", line 19, in <module>
    env_backup = deepcopy(env)
  File "/usr/lib/python3.4/copy.py", line 166, in deepcopy
    y = copier(memo)
  File "/home/ubuntu/workspace/RoomAI/roomai/common/AbstractEnv.py", line 135, in __deepcopy__
    [pe.__deepcopy__() for pe in self.__person_states_history__[i]])
IndexError: list index out of range
`

**Comment by abcp4** [comment]
Seems like it can copy now, but the object returned is an AbstractEnv(), which does not have an init function. The returned copy for the bridge case should have been an BridgeEnv, I guess.

`Traceback (most recent call last):
  File "testBridge.py", line 25, in <module>
    infos, public_state, person_states, private_state = copy_env.init({ "start_turn":0})
  File "/home/ubuntu/workspace/RoomAI/roomai/common/AbstractEnv.py", line 57, in init
    raise ("The init function hasn't been implemented")
TypeError: exceptions must derive from BaseException`

**Comment by algorithmdog** [comment]
Update the code, the bug is fixed now.  Now env can copy , and it returns the corresponding env.
